artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/thekendev/Public_data/raw/main/income_cleaned_data.csv.zip
  Local_data_file: artifacts/data_ingestion/income_cleaned_data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/cleaned_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/cleaned_data.csv
